### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by la0wei** [Cacodaimon/CacoCloud#19]
I have a vps running debian 7.I just installed lamp env and nothong configured.
Just put files in the /var/www/ folder, I navigate to xxx.com/install,nothing shows.
If navigate to xx.com, it shows the xxx.com/#/login page ,I can view the login page.
But I didn't finish the installation,ofcource I can't.
what happend?PHP scripts permisson or something else?

**Comment by Cacodaimon** [comment]
If you follow these [instructions](https://gist.github.com/Cacodaimon/2ce343ec3605de96eb14 ) which are shown in this [video](https://www.youtube.com/watch?v=6nWa1qQuda4) everything works well.

**Comment by la0wei** [comment]
can you upload the gist.github.com file in the video?
I found why it shows nothing when navi to /install/
the apache error log shows
[Fri Jan 02 14:01:16 2015] [error] [client *] PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/c.*.com/public_html/install/index.php on line 3
[Fri Jan 02 14:01:16 2015] [error] [client *] PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/c.*.com/public_html/install/index.php on line 3

**Comment by Cacodaimon** [comment]
If you have installed CacoCloud using the archive file: `http://cacodaimon.github.io/CacoCloud/download/CacoCloud.tar.gz` the autoloader should be available, but if you have cloned the source via git you have to run the composer be executing the `build.sh` script.

**Comment by Cacodaimon** [comment]
Which HTTP Server does your webhost use?

If they use an apache, is the mod_rewrite enabled?

**Comment by curtisbryant** [comment]
It's Apache (a LAMP stack), and mod_rewrite does seem to be enabled. To test, I added the code in post 9 of this thread: https://wordpress.org/support/topic/how-do-i-find-out-if-i-have-the-mod_rewrite-apache-module to my domain's .htaccess. The test succeeded in redirecting to www.google.com.

**Comment by Cacodaimon** [comment]
Its redirecting to the wrong location, the installer is located here `CacoCloud/` but it redirects to `/`, for fixing this you have to modify the `RewriteBase` in the `.htaccess` located here: https://github.com/Cacodaimon/CacoCloud/blob/master/public/install/.htaccess and here: https://github.com/Cacodaimon/CacoCloud/blob/master/public/api/1/.htaccess .

**Comment by curtisbryant** [comment]
The file /CacoCloud/public/install/.htaccess now reads:
RewriteEngine On
RewriteBase /CacoCloud/public/install/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]

The file /CacoCloud/public/api/1/.htaccess now reads:
RewriteEngine On
RewriteBase /CacoCloud/public/api/1/
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [QSA,L]

But when I go to https://mydomain.com/CacoCloud/public/install/index.php, it still redirects to https://mydomain.com/install/database and fails.

**Comment by curtisbryant** [comment]
The database is now created, but I have not been able to create the user account. It redirects to https://mydomain.com/install/user

**Comment by Cacodaimon** [comment]
I have fixed the installer, please download this version: https://github.com/Cacodaimon/CacoCloud/releases/tag/0.1.0 and fix your both `.htaccess` files after updating.

**Comment by la0wei** [comment]
Almost done.
An error occured when browser https://IP/install/
Apache error log:
[Tue Feb 10 09:02:10 2015] [error] [client *] PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/CacoCloud/public/install/index.php on line 3
[Tue Feb 10 09:02:10 2015] [error] [client *] PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/CacoCloud/public/install/index.php on line 3
[Tue Feb 10 09:03:11 2015] [error] [client *] PHP Warning:  require(vendor/autoload.php): failed to open stream: No such file or directory in /var/www/CacoCloud/public/install/index.php on line 3
[Tue Feb 10 09:03:11 2015] [error] [client *] PHP Fatal error:  require(): Failed opening required 'vendor/autoload.php' (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/CacoCloud/public/install/index.php on line 3

**Comment by sivawesome** [comment]
i am using the above version but i did not install the database

**Comment by sivawesome** [comment]
after i was deleted .htaccess file in then i get these following errors 
1. PHP imap
Needed only by the mail client.
2. HTTPS
It is suggested to run CacoCloud only with HTTPS!

after i clicked the proceed with warning button i get empty page
