### ISSUE TITLE
Undefined variable: iconDirsWritable

### ISSUE THREAD

**Issue by 9mmtylenol** [Cacodaimon/CacoCloud#20]
I get an error after all the install requirements are met and it's telling me that there is an undefined variable in the step-requirements.phtml file on line 109.

Here's the trace:
#0 /srv/http/rss/public/install/views/step-requirements.phtml(109): Slim\Slim::handleErrors(8, 'Undefined varia...', '/srv/http/rss/p...', 109, Array)
#1 /srv/http/rss/vendor/slim/slim/Slim/View.php(278): require('/srv/http/rss/p...')
#2 /srv/http/rss/vendor/slim/slim/Slim/View.php(255): Slim\View->render('./step-requirem...', NULL)
#3 /srv/http/rss/vendor/slim/slim/Slim/View.php(243): Slim\View->fetch('./step-requirem...', NULL)
#4 /srv/http/rss/vendor/slim/slim/Slim/Slim.php(757): Slim\View->display('./step-requirem...')
#5 /srv/http/rss/public/install/index.php(37): Slim\Slim->render('./step-requirem...', Array)
#6 [internal function]: {closure}()
#7 /srv/http/rss/vendor/slim/slim/Slim/Route.php(468): call_user_func_array(Object(Closure), Array)
#8 /srv/http/rss/vendor/slim/slim/Slim/Slim.php(1338): Slim\Route->dispatch()
#9 /srv/http/rss/vendor/slim/slim/Slim/Middleware/Flash.php(85): Slim\Slim->call()
#10 /srv/http/rss/vendor/slim/slim/Slim/Middleware/MethodOverride.php(92): Slim\Middleware\Flash->call()
#11 /srv/http/rss/vendor/slim/slim/Slim/Middleware/SessionCookie.php(110): Slim\Middleware\MethodOverride->call()
#12 /srv/http/rss/vendor/slim/slim/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\SessionCookie->call()
#13 /srv/http/rss/vendor/slim/slim/Slim/Slim.php(1283): Slim\Middleware\PrettyExceptions->call()
#14 /srv/http/rss/public/install/index.php(149): Slim\Slim->run()
#15 {main}

**Comment by Cacodaimon** [comment]
Thanks for the report, it should be fixed now!
